# Generated by Django 5.0.6 on 2026-05-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='medication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
