# Generated by Django 5.0.6 on 2026-05-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_medication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='medication',
            new_name='medications',
        ),
    ]
